### ISSUE TITLE
harmonize normdata uris

### ISSUE THREAD

**Issue by csae8092** [NestroyCA/baserow-entities#1]
please integrate in the processing script (maybe in the enrich script) https://github.com/acdh-oeaw/arche-assets#python to harmonize (geonames) urls, meaning replace e.g. https://www.geonames.org/3164603/venice.html with the ACDH-CH intern canonical form of geonames urls

**Comment by cfhaak** [comment]
on it, see [#a6b55cc](https://github.com/NestroyCA/baserow-entities/commit/a6b55cc9cc93cb2c88a18926a1b110ac38978f1e)

**Comment by cfhaak** [comment]
Need to dump twice if Data was changed in baserow

**Comment by csae8092** [comment]
looks quite elaborate/complicated;
* be aware that it is enough to harmonize the URIs only in the data which will be used by other applications later i.e. geojson 
* alternatively you can run a one time script to harmonize existing URIs in baserow once and then just update new onces togheter with the fetching lat/lng

* IMHO the best solution would be to modify the existing dump script in a way that the geonames uris are harmonized in the generic dump; this enhanced script could become part of https://github.com/acdh-oeaw/baserow-dump-cookiecutter

**Comment by cfhaak** [comment]
applied last suggested solution; wrote modify_dump function in generic manner, to make a broad spectrum of manipulations possible

**Comment by cfhaak** [comment]
output should be prettier
